#!/usr/bin/env bash
# Function to display information for a subdomain
display_info() {
    local subdomain=$1
    local domain=$2

    echo -n "The subdomain $subdomain.$domain is a"
    local record_type=$(dig +short $subdomain.$domain | awk 'NR==1 {print $4}')
    
    if [ -z "$record_type" ]; then
        echo " (No records found)"
    else
        local destination=$(dig +short $subdomain.$domain)
        echo " $record_type record and points to $destination"
    fi
}

nazaa.tech=$1

# If only domain parameter is provided
if [ $# -eq 1 ]; then
    SUBDOMAINS=("www" "lb-01" "web-01" "web-02")

    # Display information for each subdomain
    for SUBDOMAIN in "${SUBDOMAINS[@]}"; do
        display_info $SUBDOMAIN $DOMAIN
    done
fi

# If both domain and subdomain parameters are provided
if [ $# -eq 2 ]; then
    SUBDOMAIN=$2
    display_info $SUBDOMAIN $DOMAIN
fi
